spring:
  liquibase:
    enabled: false

  application:
    name: car-service
  datasource:
    url: jdbc:postgresql://localhost:5432/car_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - optional:configserver:http://localhost:8888/common-database
      - optional:configserver:http://localhost:8888/common-client-service
      - optional:configserver:http://localhost:8888/gateway-url


server:
  servlet:
    context-path: /car-service

springdoc:
  api-docs:
    path: v3/api-docs



